apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-rolebinding
  namespace: infrastructure
subjects:
- kind: ServiceAccount
  name: argo-rollouts
  namespace: infrastructure
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io