apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Bạn có thể thay đổi tên nếu cần
  name: argocd-clusterrole
rules:
- apiGroups: [""]
  resources: ["podtemplates"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["node.k8s.io"]
  resources: ["runtimeclasses"]
  verbs: ["list", "get", "watch"]