apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-sample
  namespace: infrastructure
spec:
  project: default
  source:
    repoURL: 'https://github.com/traina27/gitops-blue-green'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true