apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: argocd-clusterrole
  apiGroup: rbac.authorization.k8s.io