apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-full-access-binding
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: argocd-full-access-role
  apiGroup: rbac.authorization.k8s.io